# Generated by Django 5.1.3 on 2025-07-13 17:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='شماره تلفن میبایست به شکل 09123456789 باشد', regex='^09\\d{9}$')], verbose_name='شماره تلفن')),
                ('status', models.CharField(choices=[('unreaded', 'خوانده نشده'), ('rejected', 'رد شده'), ('accepted', 'پذیرفته شده')], default='unreaded', max_length=9, verbose_name='وضعیت')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=32, verbose_name='نام و نام خانوادگی')),
                ('email', models.CharField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='لطفاً یک آدرس ایمیل معتبر وارد کنید.', regex='^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$')], verbose_name='ایمیل')),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='statics\x07ssets\\img\x07bout-bg.jpg', upload_to='statics\x07ssets\\img\\', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='مطلب'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=32, verbose_name='نام نویسنده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('checking', 'درحال بررسی'), ('rejected', 'رد شده'), ('published', 'پذیرفته شده')], default='checking', max_length=9, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='like',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='مطلب'),
        ),
        migrations.AlterField(
            model_name='like',
            name='is_liked',
            field=models.BooleanField(default=False, verbose_name='لایک شده؟'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
