# Generated by Django 5.1.3 on 2025-07-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_consultation_subscriber_alter_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'وبلاگ', 'verbose_name_plural': 'وبلاگ ها '},
        ),
        migrations.AlterModelOptions(
            name='categorys',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'مشاوره', 'verbose_name_plural': 'مشاوره ها'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'لایک', 'verbose_name_plural': 'لایک ها'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'عضو خبرنامه', 'verbose_name_plural': 'اعضای خبرنامه'},
        ),
    ]
